### ISSUE TITLE
How to build this font from source ?

### ISSUE THREAD

**Issue by jilen** [agarick/agave#1] opened 2016-01-20 05:43 UTC
Acutally I am trying to create italic variant using imagemagick by shear and kerning all svgs. But I don't know How can I combine those svg glyphs ?

**Comment by blobject** [comment] 2016-01-20 13:04
Hi `jilen`. First of all, **thank you** for taking a look at my work. Yours is my first issue on github and this is totally exciting for me. :-)

Regarding the kerning and shearing of letters, I must confess to **lacking particular knowledge** in those areas. What I did was use [Inkscape](https://inkscape.org/en/) to design all the letters individually, and then I loaded them all to a single font table within [FontForge](https://fontforge.github.io/en-US/). There could be a shear/kern function within FontForge (try opening the **.sfd file** within that program), or perhaps you could connect a **script** to Inkscape?

As far as kerning goes, **_agave**_ was intended to be fixed-width (monospaced), so I hadn't made considerations beyond general **space guidelines** (i.e. hadn't considered spacing between particular combinations). Although I did have some semblance of a reason for spacing things the way I did (hm, I need to get my web server running again where I documented my reasoning), I'm sure there's a way to universally modify the side-bearings in FontForge.

I should also let you know that it's **been quite a while** since I actively maintained the font itself (and I'm **still too busy** at the moment to do so), but at the time, FreeType **automatically** applied a shear function for me that gave me a synthetic italic variant (at least on `xterm`, or was it `gvim`?). At one point, in fact, I planned to design a _real_ italic. But too bad there are only 24 hours in a day.

I realise none of what I wrote actually helps answer your question, but perhaps you could take a look at the part of [FreeType](http://freetype.org/freetype2/docs/documentation.html) source code that does the shearing? Or maybe it's in [Pango](http://www.pango.org/Download). But do be sure to check out FontForge. It's a fantastic piece of software! You say "build from source," and FontForge is probably the easiest way to generate the essential `.ttf` files.

**Comment by jilen** [comment] 2016-01-21 02:21
@agarick  You mean I shall manually load every glyph into fontforge one by one ? Saddly freetype not automatic shearing the font for Eamcs.  I have sheared all svgs, but don't know how to combine them to form a font

**Comment by blobject** [comment] 2016-01-22 14:22
Hm, if you've modified the individual `.svg` files themselves, then the best way of generating a new `.ttf` file may indeed be to import those `.svg` files one by one into FontForge, as you mention.

But I was thinking that maybe you could open the original `.sfd` file (in `-src.tar.gz`) from within FontForge and apply a shear function on the whole font table using FontForge itself. The trouble is I can't check to see if that's possible because I can't properly setup my machine at the moment, and I apologise for that.

Let me know what you decide to do. You could always switch from emacs to vim :-). I'm just kidding, hehe.

**Comment by jilen** [comment] 2016-01-23 05:28
I've already did that! Thanks @agarick

**Comment by blobject** [comment] 2016-01-25 16:18
Sure thing! Let me know if you come upon any other issues. Meanwhile, I guess I'll close this issue for now.

And thanks again for your usage. I hope that _agave_ serves you well in your monospatial endeavors despite the lack of a true italic.

**Closed as completed by blobject** 2016-01-25 16:18 UTC
Labels: question

**Comment by jilen** [comment] 2016-01-26 01:31
@agarick I like it very much. Thanks for your work
